---
title: "Report"
format: html
editor: source
embed-resources: true
---

```{r}
library(tidyverse)
library(here)
```

## Load the data
```{r}
data_raw <- read_csv(here("data", "Ross_1_study_global_include_all_CLEAN_CASE.csv"))
## Information from data dictionary:
## ross.s1.1=percentage of peers; 
## ross.s1.2=you; 
##    values: 1=sign; 2=refuse; 
##    ross.s1.1_1_TEXT & ross.s1.1_2_TEXT=percentage of peers who would respectively sign or refuse; 
## It appears that variable1 and variable2 have the same information.

## Give the key variables clearer names
data <- data_raw |> mutate(percent_guess = ross.s1.1_1_TEXT,
               choice = variable2) |> 
                ## Now:
                ## "estimate" refers to the percentage of peers who the person thinks would sign
                ## "choice" refers to whether the participant would choose to sign the agreement
  select(uID, choice, percent_guess, Country, Location)
```

## Describe the data
```{r}
data |> group_by(choice) |> 
  summarize(mean = mean(percent_guess),
            sd = sd (percent_guess))
```

## Visualize the distrubution of responses in each group
```{r}
data |> ggplot(aes(x = percent_guess, group = choice)) +
  geom_density(aes(fill = choice), alpha = .5) +
  theme_minimal()
```

## Reproduce the analyses in the paper
```{r}
data_sign <- data |> filter(choice == "Sign")
data_refuse <- data |> filter(choice == "Refuse")
x = data_sign$percent_guess
y = data_refuse$percent_guess
t.test(x, y)

## Another way to do the same thing (Recommended):
library(emmeans)
model <- lm(data = data, percent_guess ~ choice)
## Show estimated mean for each group
emmeans(model, ~ choice)

## Compare the means of each group (equivalent to a t test)
emmeans(model, ~ choice) |> 
  contrast("pairwise")
```

## Visualize the group difference
```{r}
data |> ggplot(aes(x = percent_guess, group = choice)) +
  geom_boxplot(aes(fill = choice), alpha = .5) +
  theme_minimal()
```

